# General
alias r='clear'
alias cls='clear'
alias ll='ls -al'
alias lh='ls -halt'
alias hgi='history | grep -i'
alias gi='grep -i'
alias vbrc='vi ~/.bashrc'
alias sbrc='source ~/.bashrc'
alias vi='vim'
alias fpg='find . -name \*.py | xargs grep -in --colour '
alias fpgnt='find . -name "*.py" -not -path "*/tests/*" | xargs grep -in --colour'
alias fgg='find . -name \*.go | xargs grep -in --colour '
alias fggnt='find . -name "*.go" -not -path "*/tests/*" | xargs grep -in --colour'

# Git
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push origin master'
alias gd='git diff'
alias gi='git init'
alias gl='git log'
alias gb='git branch'
alias gbm='git branch --merged'
alias gr='git remote -v'
alias gch='git checkout'
alias gchb='git checkout -b'
alias gchm='git checkout master'
alias gchd='git checkout develop'
alias gfpo='git fetch --prune origin'
alias gfpu='git fetch --prune upstream'
alias grum='git rebase upstream/master'
alias grom='git rebase origin/master'
alias grud='git rebase upstream/develop'
alias grod='git rebase origin/develop'
alias gpf='git push -f'
alias guu='gfpu;grum'
alias guo='gfpo;grom'
alias gst='git stash'
alias gsta='git stash apply'

# Docker
alias dc='docker-compose'
alias dps='docker ps'
alias di='docker images'
alias de='docker exec -it'
alias dpu='docker pull'
alias ds='docker stop'
alias drm='docker rm'
#alias drst='docker rm -vf (docker ps -aq)'
alias dpsf='docker ps --format "table {{.Names}} {{.Status}} {{.Ports}}"'
alias drmi='docker rmi (docker images -q)'

# Kubernetes
alias k='kubectl'
alias kstage='kubectl config use-context aws-stage'
alias kprod='kubectl config use-context aws-prod'
alias kcfg='kubectl config'
alias kps='kubectl get pods -n staging'
alias kpd='kubectl get pods -n dev'
alias kp='kubectl get pods'
alias kls='kubectl logs -n staging'
alias kld='kubectl logs -n dev'
alias kl='kubectl logs'
alias ke='kubectl exec -it'
alias kes='kubectl exec -it -n staging'
alias ked='kubectl exec -it -n dev'
alias ks='kubectl -n staging'
alias kd='kubectl -n dev'

alias loaddata='cd ~/code/boost-platform/everett; and docker exec -it (docker ps --format "{{.Names}}" | grep -i everett) python manage.py loaddata everett/fixtures/*json'

alias drst='docker rm -fv (docker ps -aq); and docker run -d --restart=always -v /var/run/docker.sock:/tmp/docker.sock:ro -p 80:80 -p 443:443 -p 19322:19322/udp -e DNS_IP=127.0.0.1 -e CONTAINER_NAME=http-proxy --name http-proxy codekitchen/dinghy-http-proxy; and dps -a'
